module.exports = [
    'AAPL', 'ABG', 'AFL', 'ATVI', 'AMD',
    'BABA', 'BIDU', 'BA',
    'COIN', 'CVCO', 'CLSK', 'CNK', 'CCL', 'CRWD',
    'DLTR', 'DAL', 
    'EBS', 'EHTH', 'EL', 'EHTH',
    'GMS', 'GRMN', 'GOLD', 'GNRC',
    'HASI', 'HHR', 'HIBB', 'HD', 'HAL', 'HON',
    'IBN', 'INFO', 'INTC', 
    'JBL', 'JD', 
    'KOPN',
    'FTCH', 'FSLY',
    'QDEL',
    'LGIH', 'LRN', 'LI',
    'MARA', 'MHO', 'MOMO', 'MLM', 'MSFT', 'MDB', 'MU', 'MAR',
    'NEM', 'NSP', 'NU', 'NVDA', 'NFLX',
    'OXY',
    'PAAS', 'PGTI', 'PYPL', 'PANW',
    'RIOT', 'ROG', 'RGLD', 'RSKD', 'RIDE', 'RIG',
    'SKM', 'SLAB', 'SI', 'SWCH', 'SLB', 'SKLZ', 'SPR', 'SHLS', 'SKY', 'SQM',
    'TMUS', 'TSLA', 'TWOU', 'TSN',
    'VALE', 'VIPS', 'VMC', 'VRTX', 'VEON', 'VIR',
    'UPWK',
    'WU', 'WKHS',
    'XOM', 'XPO', 
    'ZYXI', 'ZS',
];